project:
  type: website
  output-dir: site

website:
  title: "USA Spend Analysis"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: overview.ipynb
        text: Overview
      - text: Cities
        menu:
          - chicago.ipynb
          - atlanta.ipynb
          - washington_dc.ipynb
          - st_louis.ipynb
          - memphis.ipynb
          - kansas_city.ipynb
          - birmingham.ipynb
          - detroit.ipynb
          - new_orleans.ipynb
          - baltimore.ipynb
          - philly.ipynb
          - milwaukee.ipynb
          - phoenix.ipynb
          - greensboro.ipynb
          - baton_rouge.ipynb


format:
  html:
    theme: Lux
    css: styles.css
    toc: true
