project:
  type: website
  output-dir: site

website:
  title: "USA Spend Analysis"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Cities - Funding Data
        menu:
          - chicago_funding.ipynb
          - atlanta_funding.ipynb
          - washington_dc_funding.ipynb
          - st_louis_funding.ipynb
          - memphis_funding.ipynb
          - kansas_city_funding.ipynb
          - birmingham_funding.ipynb
          - detroit_funding.ipynb
          - new_orleans_funding.ipynb
          - baltimore_funding.ipynb
          - philly_funding.ipynb
          - milwaukee_funding.ipynb
          - phoenix_funding.ipynb
          - greensboro_funding.ipynb
          - baton_rouge_funding.ipynb
      - text: Cities - Analysis
        menu:
          - chicago_analysis.ipynb
          - atlanta_analysis.ipynb
          - washington_dc_analysis.ipynb
          - st_louis_analysis.ipynb
          - memphis_analysis.ipynb
          - kansas_city_analysis.ipynb
          - birmingham_analysis.ipynb
          - detroit_analysis.ipynb
          - new_orleans_analysis.ipynb
          - baltimore_analysis.ipynb
          - philly_analysis.ipynb
          - milwaukee_analysis.ipynb
          - phoenix_analysis.ipynb
          - greensboro_analysis.ipynb
          - baton_rouge_analysis.ipynb
      - href: methodology.qmd
        text: Methodology



format:
  html:
    theme: Lux
    css: styles.css
    toc: true
