---
title: "USA DOJ Spending Analysis"
toc: false
---

# How to Use This Site

This is a demo website, created by the [UChicago Crime Lab](https://crimelab.uchicago.edu/), to analyze grant funding in 15 American cities, specifically to better understand the amount of funds being allocated to violence prevention related programs. We focused on 21 grant programs [identified by the White House Office of Gun Violence Prevention](https://www.whitehouse.gov/wp-content/uploads/2024/05/CVI-Funding-Resources.pdf) which are related to violence prevention. (To read the White House press release, please [click here](https://www.whitehouse.gov/briefing-room/statements-releases/2024/05/22/readout-of-white-house-office-of-gun-violence-prevention-convening-of-local-offices-of-violence-prevention/).)

For each city, we have created a funding page, as well as an analysis page. The funding page doesn't contain any data analytics, and is meant to allow cities to easily access information pertaining to their individual grants. The analysis page provides more detail, and specifically, compares grant funding to similar cities to identify potential future places for grant applications.

Please note that everything on this website is considered a first pass analysis, and should not be taken to reflect fully accurate numbers.


# City Pages

|City|Funding Page|Analysis Page|
|---|---|---|
|Atlanta, Georgia|[Funding](/atlanta_funding.html)|[Analysis](/atlanta_analysis.html)|
|Washington, DC|[Funding](/washington_dc_funding.html)|[Analysis](/washington_dc_analysis.html)|
|St. Louis, Missouri|[Funding](/st_louis_funding.html)|[Analysis](/st_louis_analysis.html)|
|Memphis, Tennessee|[Funding](/memphis_funding.html)|[Analysis](/memphis_analysis.html)|
|Kansas City, Missouri|[Funding](/kansas_city_funding.html)|[Analysis](/kansas_city_analysis.html)|
|Birmingham, Alabama|[Funding](/birmingham_funding.html)|[Analysis](/birmingham_analysis.html)|
|Detroit, Michigan|[Funding](/detroit_funding.html)|[Analysis](/detroit_analysis.html)|
|New Orleans, Louisiana|[Funding](/new_orleans_funding.html)|[Analysis](/new_orleans_analysis.html)|
|Baltimore, Maryland|[Funding](/baltimore_funding.html)|[Analysis](/baltimore_analysis.html)|
|Philadelphia, Pennsylvania|[Funding](/philly_funding.html)|[Analysis](/philly_analysis.html)|
|Milwaukee, Wisconsin|[Funding](/milwaukee_funding.html)|[Analysis](/milwaukee_analysis.html)|
|Chicago, Illinois|[Funding](/chicago_funding.html)|[Analysis](/chicago_analysis.html)|
|Phoenix, Arizona|[Funding](/phoenix_funding.html)|[Analysis](/phoenix_analysis.html)|
|Greensboro, North Carolina|[Funding](/greensboro_funding.html)|[Analysis](/greensboro_analysis.html)|
|Baton Rouge, Louisiana|[Funding](/baton_rouge_funding.html)|[Analysis](/baton_rouge_analysis.html)|


## Data Sources:

1. DOJ Grant Funding comes from [USASpending.gov](https://www.usaspending.gov/download_center/custom_award_data)
2. Gun violence data comes from [americanviolence.org](https://www.americanviolence.org/table?compChartType=differenceChart&compare=none&crimeType=400&customCompareInterval&customTimespanInterval&metric=total&precision=monthly&selectedCensusTractsIds&selectedCitiesIds&sortColumn=name&sortPage=0&sortReversed=false&timespan=lastMonth)
